### ISSUE TITLE
Application crashing on npm start

### ISSUE THREAD

**Issue by arifmasood** [qaboxletstest/demo-api-testing#1]
I followed steps mentioned in read me. Application is crashing with below log on "npm start"

```
> demo-api-testing@1.0.0 start
> nodemon app

[nodemon] 2.0.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node app.js`
node:internal/fs/utils:313
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/Volumes/data/workspace/demo-api-testing/routes/api..\..\..\database\PFMembers.json'
    at Object.openSync (node:fs:488:3)
    at Object.readFileSync (node:fs:389:35)
    at Object.<anonymous> (/Volumes/data/workspace/demo-api-testing/routes/api/members.js:8:31)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
    at Module.require (node:internal/modules/cjs/loader:991:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Volumes/data/workspace/demo-api-testing/app.js:35:25) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Volumes/data/workspace/demo-api-testing/routes/api..\\..\\..\\database\\PFMembers.json'
}
[nodemon] app crashed - waiting for file changes before starting...
```

this code seems to be culprit as commenting this resolves crash. 
const members = JSON.parse(fs.readFileSync(filePath, 'utf-8'))

however application does not work as expected afterwards. can you please review this.

**Comment by qaboxletstest** [comment]
I believe you need to set the path of the pfmembers.json file in your case. Since it is not able to read file from that path in your case.
